### ISSUE TITLE
Mobilize worker doesn't work for enemy spies anymore

### ISSUE THREAD

**Issue by MicroVirus** [the3dfxdude/7kaa#138]
Commit a70f2f23 now explicitly prohibits players (but not AI!) from mobilising foreign workers correctly.

There is a bug in the logic now, because it refuses to mobilize a worker if it is an enemy spy (so you can also abuse the bug for spy-detection).

The logic of the change in both mobilize_worker and mobile_all_workers in confusing and prone to error, as is demonstrated by this bug.

    if( remoteAction <= COMMAND_REMOTE && !workerPtr->is_nation(firm_recno, nation_recno, 1) )

    if( !workerPtr->is_nation(firm_recno, nation_recno) )

We could fix the logic directly, but I'd like to see if we can't simplify things while we fix it.
So, why do we disallow mobilizing foreign workers? It's your building ... you should be able to evict anyone, foreign or own, from it. It's unclear to me why we would want to / need to restrict this, as it currently also limits the player (unnecessarily).

**Comment by the3dfxdude** [comment]
Fixed.

I think I had the checkSpy flag turned on in mobilize_worker thinking it would help give you the ability to quickly mobilize your own spy, but of course it just inverts the logic. The checkSpy flag is fine as it distinguishes between the firm owner mobilize permission and whether you can see because a worker is actually your spy. This logic is necessary in pretty much every firm.

There is nothing wrong with mobilize_all_worker.

The change was no restriction to evicting. The mechanism changed to evict to town due to abuse. If you want to link the right button click on a foreign worker portrait to the evict to town action, go ahead. But it's a seldom needed feature.
