### ISSUE TITLE
Unit and Race Names Need to be Seperate

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#146]
I see RACE.dbf and UNIT.dbf are grouped as one for translation. In Russian, noun and adjectives describing a nationality are different. For example: American and American is американский and американец in Russian.

**Comment by the3dfxdude** [comment]
The ADJECTIVE database field was added to facilitate the original translation. It's only used in one place in the code. I think I'll just drop the ADJECTIVE completely from being imported as a message to translate and update the message it is used in. So just treat the occurrence of the race names in what you see now as nouns to be used as labels in the UI, since that is what it will be used as.

**Comment by the3dfxdude** [comment]
Closing with commit 3e97f6f7448f8f566bba7b48cf0fa9eee0add000

Please note that the pot file has not been regenerated with these round of commits as of today. I will do that later when changes settle down.
