### ISSUE TITLE
Another Noun and Adjective Mix-up in ru.po

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#149]
I would like to use proper adjectives in Russian to modify some nouns instead of using noun modifiers in these strings:

src/OU_MONS.cpp:71
src/OF_MONS.cpp:137

Please consider splitting them up.

**Comment by the3dfxdude** [comment]
If you are referring to splitting the Lair name and Ordo name, they are already split up.

How would the stems work on what are already made up names?

**Comment by raz0rknaif** [comment]
No, I am referring to splitting "Brooksken Lair" etc. and "Brooksken Ordo" etc. to be formed as adjectives or formed into the genitive case for all Fryhtan breeds.

I do believe the stems are declinable.

"Indeclinable nouns borrowed from other languages include:

proper and common nouns ending in -э/-е, -о, -и, -у/-ю, and stressed -а/-я (foreign names and surnames ending in -a decline): меню menu, кафе cafe, па pas, step."

**Comment by the3dfxdude** [comment]
Basically what you are telling me the contextual separation provided here doesn't fix anything, because the single word is passed along directly the formatted print, which can't be corrected as is. The pretty much means any %s is subject to being a problem at some point. I'll work on it and take a note to review all %s still in existence.

**Comment by the3dfxdude** [comment]
OK I've expanded that out and a number of other things. Please remember to generate a new 7kaa.pot.

Also check the forum. I did a review to identify any remaining problems and I need some feedback.
