### ISSUE TITLE
OGAMEMP: Some text is not translating

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#180]
It is clearly translated in ru.po without fuzzy flags.

`#: src/OGAMEMP.cpp:1198
msgid ""
"Enter your 7kfans.com/forums account credentials to continue.\n"
"TIP: If you have just previously logged in using the same username, you can "
"leave your password blank, and the previous session is used."
msgstr ""
"Введите данные вашего 7kfans.com/forums аккаунта чтобы продолжить.\n"
"ПОДСКАЗКА: Если вы уже входили, используя тот же логин, вы можете оставить "
"поле пароля пустым, тогда будет использована предыдущая сессия."

#: src/OGAMEMP.cpp:1199
msgid "Username:"
msgstr "Логин:"

#: src/OGAMEMP.cpp:1200
msgid "Password:"
msgstr "Пароль:"

![image](https://user-images.githubusercontent.com/29286947/70741231-71758280-1ce0-11ea-9bf4-27766dcc59eb.png)
`

**Comment by the3dfxdude** [comment]
Please send in a pull request to clear fuzzy flags if it's fine.

gettext will mark all changes as fuzzy. This is the correct thing to do. But that means even minor punctuation, spacing all get flagged, and we broke alot of stuff that was fine and now we need to have someone fix it. That's why I rejected the last pull with minor editing, since it's starting to get much to review all of across the languages, and I can't spend extra time on each pull to make edits on top of yours if this isn't being handled upfront.

**Comment by raz0rknaif** [comment]
I mean it has no fuzzy flag already, but it is not translating for some reason.

**Comment by the3dfxdude** [comment]
Can you run tools/update-pot and check again?

**Comment by raz0rknaif** [comment]
Still nothing.

**Comment by the3dfxdude** [comment]
Closing with fb0262cdec16cf9c9c81fe95db11887b754a8978
