### ISSUE TITLE
Audio playing but no message received.

### ISSUE THREAD

**Issue by raz0rknaif** [the3dfxdude/7kaa#181]
In a game with an unexplored map, I frequently hear audio that indicates a message received, yet I see no message.

**Comment by the3dfxdude** [comment]
You are saying you are hearing the diplomatic sound, but can't see the message. The AI is sending a message but you are not allowed contact. I'll need more info on which message this is, because there are checks in place in the AI code to prevent this, and there are quite a few options.

**Comment by raz0rknaif** [comment]
I only know for sure the declare war message was being sent.

**Comment by meszaros-lajos-gyorgy** [comment]
This issue with the game is one of the oldest. It's so old I kinda got used to it. One solution would be to prevent the AI from sending messages to you, when not visible. Based on my experience these are the possible candidates for messages trying to get through:

request trade/friendly/alliance treaty (since you cannot accept these, their terminate opposites don't get triggered)
demand tribute
declare war

Also, the AI kinda thinks you are rude by not responding to these messages, which will eventually lead to them attacking you. If you would manage to fix that, the AI would be 10x more peaceful.

**Comment by the3dfxdude** [comment]
So the game devs clearly designed the "contact" aspect what that means for the AI. In terms of diplomacy, they are allowed to trigger the "demands". But they cannot trigger relation change requests, including declare war formally. And of course, they are still allowed to attack you, even if you were allied but had no contact. When the demands are triggered, certain processing happens that may lead to them considering an attack on you. If we suppress the demand messages, then that might severely limit important motivation to attack you, and they would be required to formally explore and make contact with you first. Since the AI will not be as much a challenge by suppressing these messages, due to the subsequent lack of processing the message, I won't do this.

However, suppressing the gong sound might be easy enough to prevent the buggy feel.

**Comment by the3dfxdude** [comment]
Fixed by 030e3cfee2bf88d40a0e3c903f6019e76dd53dcd

Just to be clear, the types of messages you are hearing, these demands, are primary tribute requests. There are a few others they can send, but tribute is the most likely.
