### ISSUE TITLE
Package as Flatpak

### ISSUE THREAD

**Issue by PopeRigby** [the3dfxdude/7kaa#183]
This would make it a lot easier to distribute on Linux.

**Comment by the3dfxdude** [comment]
If you have an issue with packaging, please point me to it outside of a bug report. The game is already available to you through many options, besides here.

**Comment by PopeRigby** [comment]
Sorry. Everyone uses the issue tracker differently, so I didn't know you were just using it for bugs.

**Comment by the3dfxdude** [comment]
No problem. I want to know your perspective on packaging since I was thinking about this. But I don't think we need to track this here.

**Comment by PopeRigby** [comment]
Ok. Where's the best place to discuss this?

**Comment by lennyhans** [comment]
Hi, probably the forum, check it out.
https://7kfans.com/forums/

**Comment by Mailaender** [comment]
I created https://github.com/flathub/flathub/pull/3428.

**Comment by ralflang** [comment]
A lot of desktop/GUI software, including games, is moving away from distribution native packages like deb, rpm towards container-like formats such as Flatpak in the hopes to achieve one binary to rule them all, one source to find them, one blob to bring them all, and in the darkness bind them; In the Land of Flatpak where the shadows lie.

For the vast majority of mainstream distributions, native packages already exist as well as integration patches. They are usually automatically updated by Source Services, on-upstream-release pipelines or simple github hooks so that manual intervention is only needed for edge cases which don't apply automatically. Delivering these may become old fashioned but will not become impossible anytime soon. Having a Flatpak of 7kaa can be beneficial but I don't think it is urgent in any way.

**Comment by Mailaender** [comment]
I just created a Flatpak package and uploaded it to @flathub.

**Comment by lennyhans** [comment]
Here was the last discussion [Making the flatpak](https://7kfans.com/forums/viewtopic.php?f=17&t=1143)
I also managed to create a flatpak manifest and install and play the game (with that manifest)

**Comment by Mailaender** [comment]
You are invited to join. Please let the @flathub admins know in the pull request.
