### ISSUE TITLE
Feature request, apply order to all war factory at once

### ISSUE THREAD

**Issue by meepeek** [the3dfxdude/7kaa#185]
I found myself click on each war factory and make each of them produce the same units, max quality, over and over. It would be nice if there was a way to order them all like right-click on research project in science tower.

**Comment by the3dfxdude** [comment]
Could you just use the hotkeys to cycle through the factories and edit the queues? Complete keyboard control is nearly there.

**Comment by meepeek** [comment]
It helps. Then again, would be better if there were mass command if we build up to 20. Can you gide where should I look ? May be I could patch it myself.

**Comment by the3dfxdude** [comment]
Well the actions are handled in the various detect() functions. I was looking over it before last release and I didn't do it since there was no easy way to select a unit type by the keyboard, other than making a individual hotkey for every unit type, which this game has a bundle of conflicting global hotkeys already. I want to improve the interface code a bit and do it better to deal with the situation better.

BTW, if you shift click the queue button, it does a multiple queuing.

**Comment by the3dfxdude** [comment]
So I added changed the code to support the up/down arrow in the queue to select a production item, and the minus and equal keys to add to or remove. Likewise, holding shift does batches. So if you combine this with the left/right arrows, you can cycle through your own war factories and set production queues without clicking anything.

I'm not sure if it feels natural enough. But we can reconfigure the keys and make some more polish. Just share your feedback, preferably in the forums.

**Comment by meepeek** [comment]
Thank you. Will be back after test.
