### ISSUE TITLE
AI Kingdoms eventually go bankrupt on their own

### ISSUE THREAD

**Issue by ruslan120101** [the3dfxdude/7kaa#196]
Is this intended? If playing a prolonged game with the kingdoms on most aggressive, eventually most enemy kingdoms go bankrupt and sell their buildings on their own. 

Still an active player. 

Thanks, and Long live 7kaa.

**Comment by the3dfxdude** [comment]
If you go bankrupt from negative income, then selling your buildings would help return a positive income.

Prolonged games are usually from the player turtling and manipulating the AI. The aggression setting isn't directly a difficulty setting -- it just makes AIs play more aggressively to you, and only you. It doesn't make the AI smarter. Also, there are other causes by design that can make the AI foolish towards money. So I've been sensitive towards changes these behaviors since they were fairly purposeful.

It's hard to say the extreme long games (going more than 3-4 hours on the fastest settings), were ever really intended. Pausing can quite abuse the AI to give you as much reaction time as possible. (Which reminds me, pausing can't be abused in multiplayer... should add a setting to restore original 7k behavior since it sort of breaks single player game really)

The game should be played to win by defeating your opponents. The AI doesn't do a great job at that if you know how to trick it. The game also tries to be open ended towards solving how to defeat your opponents. And with that I think it causes some confusion, and people treat the game more as a simulation, but really, it's an RTS. 7k2 did a better job at emphasizing it is an RTS.

To improve the experience, you could,
* Play on normal aggression -- it's a bit more interesting in terms of making a rich sort-of simulated fantasy environment. High or very high aggression lean more towards scenarios where the AI is stacked against you (especially very high). Maybe 'high' is a compromise. If you want to lengthen the game, lower the aggression.
* Add completion goals -- these hardly get touched on, but they are used to make the scenarios more interesting, and forces you to think

**Comment by ruslan120101** [comment]
Thank you for the pointers and for the response! Definitely turtling with no mine in my kingdom. Low resources on map (2-3), occurs on a medium pace setting with no pauses (that's cheating!), eventually the AI kingdoms unify and then go bankrupt. The turtling + defense strategy is probably what does it. 

Apologies for classifying this as an issue, wanted to bring this up in case it was..

Thanks for taking up the reins on this.
