### ISSUE TITLE
Extra Whitespace in the Manual

### ISSUE THREAD

**Issue by tmr83** [the3dfxdude/7kaa#209]
There are some places in the manual with extra whitespace due to using \clearpage. I will not show them here because I removed some text which always messes up the rest of the manual for that chapter. I am trying to avoid using \clearpage and will remove them.

There is also extra whitespace for a tabular environment between \subsection{Mouse Commands} and \subsection{Hot Keys}.

**Comment by UndescriptDev** [comment]
The issues described here are no longer a problem due to not using as many \clearpage commands and switching to a longtable env, but in chapter 16: Seats of Power & Greater Beings, there is some improper use of whitespace by Latex. Idk why, but it appears Latex is trying to fill the whole page with the sectioning, image, and text which results in the added whitespace.

**Comment by the3dfxdude** [comment]
I suppose there was a cleanup done. And it has looked better since this indeed. Closing. Thanks for the work.
