### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by jorgesumle** [the3dfxdude/7kaa#222]
There shouldn't be a comma between double quotes that are intended just for a letter. Or is it some grammar rule that I'm missing?

> When the button is set to **"T,"** the Ship will continue to ply its trade route.
If at any time you wish to regain total control over that Ship you must Click on the button, changing it to a "C".

Maybe it should say 'set to "T",'

> When the button is set to **"C,"** you can use the Ship for other purposes, such as transporting Soldiers or for war at sea.  Once those tasks finished, Clicking on the "C" Button will change it back into a "T".

Maybe it should say 'set to "C",'

**Comment by jorgesumle** [comment]
Oh, and there is a missing comma.

> If at any time you wish to regain total control over that Ship you must Click on the button, changing it to a "C".

It should say 'If at any time you wish to regain total control over that Ship, you must Click on the button, changing it to a "C".'

**Comment by jorgesumle** [comment]
> "A quick -- although sometimes expensive -- way of building a multi-cultural "

> "one or -- better yet -- several Porcupines into the midst of the enemy. "

I'd say that it's better to use a [dash](https://en.wikipedia.org/wiki/Dash).

**Comment by the3dfxdude** [comment]
These are stylistic questions. The comma placement is acceptable either way.

The dash won't matter. We cannot support utf8, so it will have to be a double dash (minus) anyway. A double dash is also acceptable.

Stylistic changes are ok, but I would highly suggest to minimize breakage of translations for submitting these kinds of changes.

**Comment by jorgesumle** [comment]
> The comma placement is acceptable either way.

See https://english.stackexchange.com/questions/6786/comma-in-conditional-sentence-and-in-antithesis.

**Comment by the3dfxdude** [comment]
There is no grammatical or typo error. As being a stylistic question I probably should say, I'd accept changing it if this is a clause that is stylistically inconsistent with the majority of the written messages and if the check-in doesn't leave all the translations broken for a punctuation change. I don't want to start creating a mess of small changes across the board that causes more work for changing style.

**Comment by jorgesumle** [comment]
> You will be victorious when there is only one kingdom remaining; your own. 

The semicolon is wrongly used here. A colon should be used instead.

**Comment by jorgesumle** [comment]
![Captura de ecrã de 2021-10-15 14-20-32](https://user-images.githubusercontent.com/14212780/137485775-866b0392-4f31-41d5-bc2a-b8157cf18b77.png)
Here there are two spaces after the second stop, but it should be one.

**Comment by jorgesumle** [comment]
![Captura de ecrã de 2021-10-17 15-28-26](https://user-images.githubusercontent.com/14212780/137629173-a5aaefe1-50c5-4b7a-ad73-9de38194fd3b.png)

Here there are two spaces after the stop, but it should be one.

**Comment by the3dfxdude** [comment]
I corrected the typos and clearly incorrect spacing.

I added the commas, although this is tricky, as I don't know if the translators followed the message punctuation exactly or extracted whatever invisible comma meaning could be there. Adding punctuation like this might not really be beneficial, and if I accept it, I might have to force all of the translations to go fuzzy anyway, to get proper review. In these cases it looks ok, although the passage for the "Make or Break" scenario description in Esperanto looks incomplete. Please fix it.

I did not replace the semicolons. This follows the previous reasons above, and I don't agree with the change in the text.

Finally the two spaces after a stop-- this is actually a convention used in the writing industry, one which the original developers were following. So it is actually everywhere in the game, more than you show. But unfortunately, due to how FileTxt files work, it causes single spaces at line breaks, making the game inconsistent. This can be fixed, and I would give the preference to the single space. Fixing to two space is also possible in these passages, but more messy. However, even the single space fix is alot of work, given it's pretty much everywhere. Then there is also the issue that translators may have followed the convention. I don't think it's worth it right now, but if someone can show they can do it well, I'll accept it.

Thank you for pointing out the issues you came across when translating.
