### ISSUE TITLE
spy (general) inside enemy ship but ship not visible

### ISSUE THREAD

**Issue by watery** [the3dfxdude/7kaa#233]
I guess this is a bug, moreover I could see inside the ship while it was outside fog:

![7kaa-invisible-ship-spy](https://user-images.githubusercontent.com/3211180/160288383-5abfab2f-c06d-40d7-babe-a9961660c7ee.png)

See save `GAMA_002.SAV`: [7kaa-20220327.zip](https://github.com/the3dfxdude/7kaa/files/8357927/7kaa-20220327.zip)

**Comment by the3dfxdude** [comment]
Since the info pane for a ship checks for a spy, then I suppose the vision code is just unfinished. Since I was just working with similar code, I think I can get it done pretty easily.

**Comment by the3dfxdude** [comment]
So enabling the vision is not a big deal, and this as I mentioned is tweaking code that is unfinished in terms of gameplay. It's very likely that you were supposed to see the location because the info pane is enabled, when you are allowed to select it. But having vision is not much useful for these instances, as you can't actually do anything, since no further development occurred (obvious as it was not really tested with fog). What should be done from here, will be for another time.
