### ISSUE TITLE
Fullscreen performance problem

### ISSUE THREAD

**Issue by cleeus** [the3dfxdude/7kaa#26]
Heyho,

5790ff0300f8405cb415bf902d01b9a12e50dd55 causes horrible performance in fullscreen mode for me (lots of CPU usage, low FPS). A similar commit was reverted some time ago, see c668f4c7aa49cb69e1e04d06a62fe1e39175307e.

**Comment by the3dfxdude** [comment]
This is a pull candidate after tagging 2.14.5.

**Comment by the3dfxdude** [comment]
The performance problem with older machines should be greatly fixed by 477fabb9edc72156f580a7694a686e624f0f6eba if you have any machine from the last decade or so. On my slowest machine, speed 9 is fairly playable, going from 1 to 30 fps. The adaptive framerate code didn't really help as doubling the wait (34ms) between draws didn't really bump it above 1. I had to bump it to as much as 100ms for it start to be playable, and a little higher to really eliminate the unnecessary redrawing. That number really came down to poorly utilizing the hardware with flip being able to be called almost anywhere. And flip became alot more expensive than in SDL2 than SDL1.

I don't see much of a need for an adaptive framerate after this since, there is alot more that should be done that can utilize SDL2, which in turn could really be beneficial for everyone, and that the game should not really be that much slower than what it was on a pentium 90, provided you do have a decent OpenGL driver.
