### ISSUE TITLE
Menus aren't translatable

### ISSUE THREAD

**Issue by jorgesumle** [the3dfxdude/7kaa#268]
The menus aren't translatable. I think they are images, so the solution can be either make also translated images or make the menus with code.

**Comment by lennyhans** [comment]
In fact, almost all buttons are based on raster images, the only way to solve this is:
- rework the buttons (bitmaps) to remove the text 
- and find a suitable font to put the text in the code. 
- Put the text on every cleared button
- Update the pot with gettext

Currently there is no effort in that direction (from what I remember)

**Comment by the3dfxdude** [comment]
Yes, this issue is acknowledged. It's a large fix in effort to get to the point of completing this. Placing this issue in the 7kfans.com forum topic here and will be tracked there.
https://7kfans.com/forums/viewtopic.php?f=20&t=1291&p=9701#p9701

The primary repository mirror and other services will be at sourceforge.net.
