### ISSUE TITLE
build failer with gcc6

### ISSUE THREAD

**Issue by michelmno** [the3dfxdude/7kaa#63]
build failer with gcc6

as reported by last openSUSE Tumbleweed pending build at (1)
I retrieved the log an added as
[7kaa_osc_ppc64le_build_failure.txt](https://github.com/the3dfxdude/7kaa/files/318310/7kaa_osc_ppc64le_build_failure.txt)
attachment to this issue

(1) https://build.opensuse.org/package/live_build_log/openSUSE:Factory:PowerPC/7kaa/standard/ppc64le

**Comment by michelmno** [comment]
below the proposed patch:
[gcc6_char_cast.patch.txt](https://github.com/the3dfxdude/7kaa/files/318315/gcc6_char_cast.patch.txt)

**Comment by MicroVirus** [comment]
It's failing on the 'warnings' by `-Wnarrowing` in OBULLET.cpp, on the lines:

    static char spiral_x[SCAN_RANGE*SCAN_RANGE] = 
	    { 0, 0,-1, 0, 1,-1,-1, 1, 1, 0,-2, 0, 2, -1,-2,-2,-1, 1, 2, 2, 1,-2,-2, 2, 2};
    static char spiral_y[SCAN_RANGE*SCAN_RANGE] = 
	    { 0,-1, 0, 1, 0,-1, 1, 1,-1,-2, 0, 2, 0, -2,-1, 1, 2, 2, 1,-1,-2,-2, 2, 2,-2};

Are `char`s unsigned in this gcc6 instance? That might give issues all over the code, not just at this line where it explicitly warns.

**Comment by michelmno** [comment]
only as reference the major issues with gcc6: https://gcc.gnu.org/gcc-6/porting_to.html

**Comment by the3dfxdude** [comment]
So this is an issue with PowerPC? Frankly, it seems pointless to include 7K in your PPC build system, since the code has to be completely revamped for byte swapping. The game can't work on that architecture at all. Has anyone actually ever run it to see if it worked after you built it? Is there really still a SuSE PPC anymore?

That error does look legitimate per arch -- but I wonder how many applications never worked on PPC in the first place. That error should had been caught in gcc prior to version 6, and if not, it was plain broken.

I think I'll make a call now and reject this issue. The game does not support PPC. The only mention for SDL support of PPC is for v1.2 for PPC Mac, which means the only thing the game could be compiled on is PPC Linux -- not likely anything that is actually running on actual hardware these days. I can't just fix this one thing since I'll need to fix all of the support issues anyway to make a difference. And the lack of any possibility that someone has a machine that would use this a motivating factor.

**Comment by the3dfxdude** [comment]
So there is some support out there in the server market.
https://www.ibm.com/support/knowledgecenter/linuxonibm/liaam/liaamdistros.htm

But someone would have to explain the platform they are using, what needs to be done, and have an actual system to test this on. This isn't really about gcc6.
